atk JabAttack : 0x1
atk FTiltAttack : 0x2
atk UTiltAttack : 0x3
atk DTiltAttack : 0x4
atk FSmashAttack : 0x5
atk USmashAttack : 0x6
atk DSmashAttack : 0x7
atk NBGroundAttack : 0x8
atk FBGroundAttack : 0x9
atk UBGroundAttack : 0xA
atk DBGroundAttack : 0xB
atk GrabAttack : 0xC
atk NoAttack : 0xD
atk NAirAttack : 0xE
atk FAirAttack : 0xF
atk BAirAttack : 0x10
atk UAirAttack : 0x11
atk DAirAttack : 0x12
atk NSpecialAirAttack : 0x13
atk SSpecialAirAttack : 0x14
atk USpecialAirAttack : 0x15
atk DSpecialAirAttack : 0x16