//Automatically collected from OpenSA wiki.
sact SpecialNStart : 0x1CE
sact SpecialNLoop : 0x1CF
sact SpecialNEnd : 0x1D0
sact SpecialAirNStart : 0x1D1
sact SpecialAirNLoop : 0x1D2
sact SpecialAirNEnd : 0x1D3
sact SpecialSStart : 0x1D4
sact SpecialS : 0x1D5
sact SpecialSEnd : 0x1D6
sact SpecialAirSStart : 0x1D7
sact SpecialAirS : 0x1D8
sact SpecialAirSEnd : 0x1D9
sact SpecialHiHold : 0x1DA
sact SpecialHiHoldAir : 0x1DB
sact SpecialHi : 0x1DC
sact SpecialHiLanding : 0x1DD
sact SpecialHiFall : 0x1DE
sact SpecialHiBound : 0x1DF
sact SpecialLwStart : 0x1E0
sact SpecialLwLoop : 0x1E1
sact SpecialLwHit : 0x1E2
sact SpecialLwEnd : 0x1E3
sact SpecialAirLwStart : 0x1E4
sact SpecialAirLwLoop : 0x1E5
sact SpecialAirLwHit : 0x1E6
sact SpecialAirLwEnd : 0x1E7
sact FinalStart : 0x1E8
sact FinalEnd : 0x1E9
sact FinalAirStart : 0x1EA
sact FinalAirEnd : 0x1EB
sact AppealSStartL : 0x1EC
sact AppealSStartR : 0x1ED
sact AppealSL : 0x1EE
sact AppealSR : 0x1EF
sact AppealSEndL : 0x1F0
sact AppealSEndR : 0x1F1
