//Automatically collected from OpenSA wiki.
sact SpecialN : 0x1CE
sact SpecialNCancel : 0x1CF
sact SpecialNHold : 0x1D0
sact SpecialNStart : 0x1D1
sact SpecialAirN : 0x1D2
sact SpecialAirNStart : 0x1D3
sact Special : 0x1D4
sact SpecialAir : 0x1D5
sact SpecialS : 0x1D6
sact SpecialAirS : 0x1D7
sact SpecialHi : 0x1D8
sact SpecialAirHi : 0x1D9
sact SpecialLw : 0x1DA
sact SpecialLwRoll : 0x1DB
sact SpecialLwEnd : 0x1DC
sact SpecialAirLw : 0x1DD
sact SpecialAirLwEnd : 0x1DE
sact FinalSZerosuit : 0x1DF
sact FinalAirSZerosuit : 0x1E0
sact Final : 0x1E1
sact FinalAir : 0x1E2
sact FinalEnd : 0x1E3
sact FinalAirStart : 0x1E4
sact FinalEnd_1 : 0x1E5
sact FinalStart : 0x1E6
sact FinalU : 0x1E7
sact FinalD : 0x1E8
sact FinalAirU : 0x1E9
sact FinalAirD : 0x1EA
sact ArmorReleaseSZerosuit : 0x1EB
